import streamlit as st
import pandas as pd
import io

# Page setup
st.set_page_config(page_title="Salon Analytics Suite", page_icon="💇‍♀️", layout="centered")

st.title("💇‍♀️ Salon Check-and-Balance Suite")
st.write("Easily extract individual worker metrics or analyze entire department performance from your daily records.")

st.markdown("---")

# 1. Master File Uploader
uploaded_file = st.file_uploader("Upload your Salon Master Spreadsheet (Excel or CSV)", type=["xlsx", "csv"])

if uploaded_file is not None:
    try:
        # Load file correctly
        if uploaded_file.name.endswith('.csv'):
            df = pd.read_csv(uploaded_file)
        else:
            df = pd.read_excel(uploaded_file)
            
        st.success("Master salon sheet parsed successfully!")
        
        # Clean column names (strip whitespace)
        df.columns = df.columns.str.strip()
        
        # Ensure 'Price' column is treated purely as numeric data for math
        if 'Price' in df.columns:
            df['Price'] = pd.to_numeric(df['Price'], errors='coerce')

        # --- SYSTEM TABS ---
        tab1, tab2 = st.tabs(["👤 Individual Worker View", "🏬 Department Deep-Dive"])

        # =========================================================
        # TAB 1: INDIVIDUAL WORKER VIEW
        # =========================================================
        with tab1:
            st.subheader("Filter Solely by Worker Name")
            
            if 'Worker Name' in df.columns:
                unique_workers = sorted(df['Worker Name'].dropna().unique())
                selected_worker = st.selectbox("Select a stylist/worker:", unique_workers, key="worker_select")
                
                worker_df = df[df['Worker Name'] == selected_worker]
                
                total_services = len(worker_df)
                revenue = worker_df['Price'].sum() if 'Price' in df.columns else 0.0
                
                m_col1, m_col2 = st.columns(2)
                m_col1.metric(f"Services Done by {selected_worker}", f"{total_services}")
                m_col2.metric(f"Revenue Generated by {selected_worker}", f"${revenue:,.2f}")
                
                st.dataframe(worker_df, use_container_width=True)
                
                buffer_w = io.BytesIO()
                with pd.ExcelWriter(buffer_w, engine='openpyxl') as writer:
                    worker_df.to_excel(writer, index=False, sheet_name=selected_worker)
                
                st.download_button(
                    label=f"📥 Download {selected_worker}'s Row Data",
                    data=buffer_w.getvalue(),
                    file_name=f"{selected_worker}_individual_report.xlsx",
                    mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    key="dl_worker"
                )
            else:
                st.warning("⚠️ Your sheet is missing a 'Worker Name' column.")

        # =========================================================
        # TAB 2: DEPARTMENT ANALYTICS VIEW
        # =========================================================
        with tab2:
            st.subheader("Filter Whole Department Data")
            
            if 'Department' in df.columns:
                unique_depts = sorted(df['Department'].dropna().unique())
                selected_dept = st.selectbox("Select salon department:", unique_depts, key="dept_select")
                
                dept_df = df[df['Department'] == selected_dept]
                
                dept_services = len(dept_df)
                dept_revenue = dept_df['Price'].sum() if 'Price' in df.columns else 0.0
                
                d_col1, d_col2 = st.columns(2)
                d_col1.metric(f"Total {selected_dept} Tickets", f"{dept_services}")
                d_col2.metric(f"Total {selected_dept} Revenue", f"${dept_revenue:,.2f}")
                
                st.dataframe(dept_df, use_container_width=True)
                
                buffer_d = io.BytesIO()
                with pd.ExcelWriter(buffer_d, engine='openpyxl') as writer:
                    dept_df.to_excel(writer, index=False, sheet_name=selected_dept)
                
                st.download_button(
                    label=f"📥 Download {selected_dept} Department Dataset",
                    data=buffer_d.getvalue(),
                    file_name=f"{selected_dept}_department_report.xlsx",
                    mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    key="dl_dept"
                )
            else:
                st.warning("⚠️ Your sheet is missing a 'Department' column.")
                
    except Exception as e:
        st.error(f"Error reading dataset files: {e}")
